# Generated by Django 5.0 on 2024-03-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_created_at_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
    ]
