# Generated by Django 5.0 on 2024-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_product_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
